variable "cluster_name" {}
variable "node_role_arn" {}
variable "node_name" {}
variable "node_version" {}
variable "subnet_ids" {}
variable "disk_size" {}
variable "instance_type" {}
variable "ami_type" {}
variable "ec2_ssh_key" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}