variable "cidr_block_sub_2a" {}
variable "cidr_block_sub_2b" {}
variable "cidr_block_sub_2c" {}
variable "az_2a" {}
variable "az_2b" {}
variable "az_2c" {}
variable "vpc_id" {}
variable "tag_Name_2a" {}
variable "tag_Name_2b" {}
variable "tag_Name_2c" {}
variable "tag_Env" {}
variable "tag_Owner" {}
